### ISSUE TITLE
System Freeze when cancel chat heads

### ISSUE THREAD

**Issue by fabriziogueli** [flipkart-incubator/springy-heads#17]
Hi,
I want to report a bug.
I  tried the PlayStore version (Springy chat head service).
When i delete the chat heads the system freeze and i have to reboot.

**Comment by thekirankumar** [comment]
I am not able to reproduce it. Do you have exactset of steps or maybe a video ?

**Comment by fabriziogueli** [comment]
1) Open the App
2) Press the back button and go to home
3) Delete all the Bubbles
4) The launcher is freezed

I tried with the master branch and the problem does not occurs.
But i see this error in the logcat:

`01-31 19:59:18.030 7248-7248/? E/ActivityThread: Activity com.flipkart.springyheads.demo.FloatingActivity has leaked ServiceConnection com.flipkart.springyheads.demo.FloatingActivity$1@6f511b that was originally bound here
                                                 android.app.ServiceConnectionLeaked: Activity com.flipkart.springyheads.demo.FloatingActivity has leaked ServiceConnection com.flipkart.springyheads.demo.FloatingActivity$1@6f511b that was originally bound here
                                                     at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1336)
                                                     at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1231)
                                                     at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1478)
                                                     at android.app.ContextImpl.bindService(ContextImpl.java:1450)
                                                     at android.content.ContextWrapper.bindService(ContextWrapper.java:636)
                                                     at com.flipkart.springyheads.demo.FloatingActivity.onCreate(FloatingActivity.java:53)
                                                     at android.app.Activity.performCreate(Activity.java:6664)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                                                     at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:154)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

Also, i noticed that sometimes if i play a little, the back button does not work and i have to terminate the app from the settings `
