### ISSUE TITLE
Crash on removing the last chat head form view

### ISSUE THREAD

**Issue by GurpreetSK95** [flipkart-incubator/springy-heads#30]
A NullPointerException is thrown whenever the last head is removed from the view, thus causing the application to crash.
```

06-23 16:27:05.049 21780-21780/me.gurpreetsk.soundrecordingwithtts E/MaximizedArrangement: onSpringAtRest: 
                                                                                           java.lang.NullPointerException: Attempt to invoke virtual method 'com.facebook.rebound.Spring com.facebook.rebound.Spring.removeListener(com.facebook.rebound.SpringListener)' on a null object reference
                                                                                               at com.flipkart.chatheads.arrangement.MaximizedArrangement$2.onSpringAtRest(MaximizedArrangement.java:118)
                                                                                               at com.facebook.rebound.Spring.advance(Spring.java:445)
                                                                                               at com.facebook.rebound.BaseSpringSystem.advance(BaseSpringSystem.java:129)
                                                                                               at com.facebook.rebound.BaseSpringSystem.loop(BaseSpringSystem.java:143)
                                                                                               at com.facebook.rebound.AndroidSpringLooperFactory$ChoreographerAndroidSpringLooper$1.doFrame(AndroidSpringLooperFactory.java:117)
                                                                                               at android.view.Choreographer$CallbackRecord.run(Choreographer.java:872)
                                                                                               at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                                               at android.view.Choreographer.doFrame(Choreographer.java:618)
                                                                                               at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                                               at android.os.Handler.handleCallback(Handler.java:751)
                                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                               at android.os.Looper.loop(Looper.java:154)
                                                                                               at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
06-23 16:27:05.052 21780-21780/me.gurpreetsk.soundrecordingwithtts E/WindowManagerContainer: updateLayout: 
                                                                                             java.lang.IllegalArgumentException: View=com.flipkart.chatheads.container.WindowManagerContainer$MotionCaptureView{ca123f3 V.ED..... ......I. 0,0-1080,1731} not attached to window manager
                                                                                                 at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:473)
                                                                                                 at android.view.WindowManagerGlobal.updateViewLayout(WindowManagerGlobal.java:368)
                                                                                                 at android.view.WindowManagerImpl.updateViewLayout(WindowManagerImpl.java:99)
                                                                                                 at com.flipkart.chatheads.container.WindowManagerContainer.updateLayout(WindowManagerContainer.java:214)
                                                                                                 at com.flipkart.chatheads.container.WindowManagerContainer.onArrangementChanged(WindowManagerContainer.java:204)
                                                                                                 at com.flipkart.chatheads.container.DefaultChatHeadManager.setArrangementImpl(DefaultChatHeadManager.java:388)
                                                                                                 at com.flipkart.chatheads.container.DefaultChatHeadManager.onMeasure(DefaultChatHeadManager.java:184)
                                                                                                 at com.flipkart.chatheads.container.HostFrameLayout.onLayout(HostFrameLayout.java:27)
                                                                                                 at android.view.View.layout(View.java:17637)
                                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                                                 at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2346)
                                                                                                 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2068)
                                                                                                 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                                                                 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6338)
                                                                                                 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                                                 at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                                                 at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                                                 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                                                 at android.os.Handler.handleCallback(Handler.java:751)
                                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                                 at android.os.Looper.loop(Looper.java:154)
                                                                                                 at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by icoolguy1995** [comment]
You need to update facebook rebound from lib's gradle

**Comment by cazador4** [comment]
I've already update the lib but error still occurs. Any idea?

**Comment by cazador4** [comment]
@icoolguy1995 please look at my fork.

**Comment by HungTDO** [comment]
@GurpreetSK95 Plz edit code in MinimizedArrangement.java#getBundle() 

>     if (hero != null && hero.getHorizontalSpring() != null) {
>             relativeXPosition = hero.getHorizontalSpring().getCurrentValue() * 1.0 / maxWidth;
>             relativeYPosition = hero.getVerticalSpring().getCurrentValue() * 1.0 / maxHeight;
>         }

All worked.

**Comment by HungTDO** [comment]
@GurpreetSK95 Just check null:
[Link](https://github.com/cazador4/springy-heads/commit/b12bc887ac0d5f36d060e8da5b7f1ff61cfefb64#diff-17d2861efe0ca5aea51e26233a4995efR110)
@cazador4  :+1: 
But still error in MinimizedArrangement.java class.
same error & same solutions: check null for hero on onDeactivate() method:
```
if (hero != null) {
            if (hero.getHorizontalSpring() != null) {
                hero.getHorizontalSpring().removeListener(horizontalHeroListener);
            }
            if (hero.getVerticalSpring()!= null) {
                hero.getVerticalSpring().removeListener(verticalHeroListener);
            }
        }
```
